---
# Common paths and names
middleware_home: "{{ fmw_base }}/product/Oracle_Home"

middleware_common_home: "{{ middleware_home }}/oracle_common"

# Applications Home directory
applications_home: "{{ fmw_base }}/config/applications"

# Base directory 
fmw_installer_folder: "{{ fmw_base }}/installer"

# Software and configuration main directory
fmw_base: "/oracle/fmw12.1.3"

# Fusion Middleware installer
fmw_installer: "fmw_12.1.3.0.0_infrastructure.jar"

# Domain Name
domain_name: "adf_domain"

# Domain Home directory
domain_home: "{{ domains_home }}/{{ domain_name }}"

# Home directory for all domains
domains_home: "{{ fmw_base }}/config/Domains"

# Nodemanager and server settings
nodemanager_listen_port: "5556"
nodemanager_listen_address: "localhost"
nodemanager_home: "{{ fmw_base }}/config/nodemanagers/{{ domain_name }}"
nodemanager_username: "weblogic"

managed_server_name: "adfsrv1"
managed_server_port: "7003"

admin_server_name: "AdminServer"
admin_server_hostname: "localhost"
admin_server_port: "7001"

# Weblogic server admin name
weblogic_admin: "weblogic"

# Weblogic server Home directory
weblogic_home: "{{ middleware_home }}/wlserver"

# Fully Qualified Domain Name of server
server_hostname: "{{ ansible_fqdn }}"

# Path to ld libraries
ld_library_path: "{{ weblogic_home }}/server/native/linux/x86_64"

# Prefix for repository
repository_prefix: "wls12c2"


