---
# Deploying of the playbook takes about 22 minutes on a virtual machine with 1 CPU and 1 GB RAM
- name: Configure CentOS 6.7 with WebLogic 12c domain
  hosts: weblogic
  become: True
  vars_files:
    # User defined variables for infrastructure
    - group_vars/common.yml
    # User Passwords
    - group_vars/secrets.yml
    # WebLogic Server variables
    - group_vars/mw_vas.yml
  
  roles:
    - linux-wls
    - jdk-wls
    - fmw-software
    - fmw-domain