---
# List of dependences
packages_list:
  - 'binutils'
  - 'compat-libcap1'
  - 'compat-libstdc++-33'
  - 'gcc'
  - 'gcc-c++'
  - 'glibc'
  - 'glibc-devel'
  - 'libaio'
  - 'libaio-devel'
  - 'libgcc'
  - 'libstdc++'
  - 'libstdc++-devel'
  - 'ksh'
  - 'make'
  - 'sysstat'
  - 'libselinux-python'

# Kernel parameters for Fusion Midleware server
kernel_params:
  # max shared seg size (bytes)
  kernel.shmmax: 1073741824
  # (SHMMAX/getpagesize()*(SHMMNI/16)) 
  kernel.shmall: 262144
  # For 1Gbps with 1ms latency 16MB buffer
  net.core.rmem_max: 16777216
  net.core.wmem_max: 16777216
  net.ipv4.tcp_rmem: 4096 87380 16777216
  net.ipv4.tcp_wmem: 4096 65536 16777216
  # Minimize swap file use
  vm.swappiness: 10
  vm.dirty_background_ratio: 5
  vm.dirty_ratio: 10
  # Max open file descriptors 512 * db processes + room for os
  fs.file-max: 131072
  # Shorten keep alive of connections
  net.ipv4.tcp_keepalive_time: 300
  net.ipv4.tcp_keepalive_intvl: 60
  net.ipv4.tcp_keepalive_probes: 10

# Oracle user limits
# Soft limit number of open files
soft_no_file: 4096
# Hard limit for number of open files
hard_no_file: 65536
# Soft limit for number of processes
soft_nproc: 2047
# Hard limit for number of processes
hard_nproc: 16384