---
# ==> Install JDK
- name: Install JDK | Ensure dependences are present
  yum:
    name: "{{ item }}"
  with_items:
    - wget

- name: Install JDK | Download installation files
  get_url: 
    url: "{{ jdk_url }}" 
    dest: "/tmp/"
    headers: "Cookie: oraclelicense=accept-securebackup-cookie;"
    force: no

- name: Install JDK | Install jdk
  yum:
    name: "/tmp/{{ jdk_rpm }}"
    state: "present"

- name: Install JDK | Change entropy device for java
  replace:
    dest: "{{ jdk_folder }}/jre/lib/security/java.security"
    regexp: "urandom"
    replace: "./urandom"
    backup: yes

- name: Install JDK | Add JAVA_HOME environment variariables in bashrc
  lineinfile: 
    dest: "/home/{{ oracle_user }}/.bashrc" 
    line: "export JAVA_HOME={{ jdk_folder }}"

- name: Install JDK | Add Java bin folder to path in bashrc
  lineinfile: 
    dest: "/home/{{ oracle_user }}/.bashrc" 
    line: "export PATH=$PATH:$JAVA_HOME/bin"
