---

# Default Java distribution [jdk|jre]
oracle_java_distribution: jre

# Default major version
oracle_java_version_major: 1

# Default minor version
oracle_java_version_minor: 7

# Default patch version
oracle_java_version_patch: 0

# Default update version
oracle_java_version_update: 80

# Default architerture
oracle_java_arch: 64

# Default development branch
oracle_java_branch: "15"

# Indicates whether this Java versin should be set as default alternative
oracle_java_default: false

# Flag which triggers the package cleaning
oracle_java_finish: false

# URL to Java distribution [jdk|jre]
java_url: "http://download.oracle.com/otn-pub/java/jdk/{{ oracle_java_version_minor }}u{{ oracle_java_version_update }}-b{{ oracle_java_branch }}/{{ oracle_java_distribution }}-{{ oracle_java_version_minor }}u{{ oracle_java_version_update }}-linux-x{{ oracle_java_arch }}.rpm"

# Version as a string
oracle_java_version_string: '{{ oracle_java_version_major }}.{{ oracle_java_version_minor }}.{{ oracle_java_version_patch }}_{{ oracle_java_version_update }}'

# Directory name
oracle_java_version_dir: '{{ oracle_java_distribution }}{{ oracle_java_version_string }}'

# Java8 has the version as part of the package name
oracle_java_distribution_string: '{{ oracle_java_distribution + oracle_java_version_string if oracle_java_version_minor == 8 else oracle_java_distribution }}'

# Alternatives priority
oracle_java_version_priority: '{{ oracle_java_version_major}}{{ "%02d" % oracle_java_version_minor }}{{ "%02d" % oracle_java_version_patch }}{{ "%03d" % oracle_java_version_update }}'
